version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.15.2
    volumes:
      - ./config/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - prometheus-pushgateway:prometheus-pushgateway
    restart: always
  prometheus-pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
  grafana:
    image: grafana/grafana
    user: "104"
    links:
      - prometheus:prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/:/etc/grafana/provisioning/
    env_file:
      - ./config/grafana/config.monitoring
    restart: always
